//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Владелец {
    
    private string идField;
    
    private string наименованиеField;
    
    private string официальноеНаименованиеField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Наименование {
        get {
            return this.наименованиеField;
        }
        set {
            this.наименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ОфициальноеНаименование {
        get {
            return this.официальноеНаименованиеField;
        }
        set {
            this.официальноеНаименованиеField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Группы {
    
    private string идField;
    
    private ГруппыГруппа[] группаField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Группа", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ГруппыГруппа[] Группа {
        get {
            return this.группаField;
        }
        set {
            this.группаField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ГруппыГруппа {
    
    private string идField;
    
    private string наименованиеField;
    
    private string родительField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Наименование {
        get {
            return this.наименованиеField;
        }
        set {
            this.наименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Родитель {
        get {
            return this.родительField;
        }
        set {
            this.родительField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class КоммерческаяИнформация {
    
    private КоммерческаяИнформацияКлассификатор[] классификаторField;
    
    private КоммерческаяИнформацияПакетПредложений[] пакетПредложенийField;
    
    private string версияСхемыField;
    
    private string датаФормированияField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Классификатор", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public КоммерческаяИнформацияКлассификатор[] Классификатор {
        get {
            return this.классификаторField;
        }
        set {
            this.классификаторField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ПакетПредложений", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public КоммерческаяИнформацияПакетПредложений[] ПакетПредложений {
        get {
            return this.пакетПредложенийField;
        }
        set {
            this.пакетПредложенийField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ВерсияСхемы {
        get {
            return this.версияСхемыField;
        }
        set {
            this.версияСхемыField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ДатаФормирования {
        get {
            return this.датаФормированияField;
        }
        set {
            this.датаФормированияField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class КоммерческаяИнформацияКлассификатор {
    
    private string идField;
    
    private string наименованиеField;
    
    private Владелец[] владелецField;
    
    private Группы[] группыField;
    
    private КоммерческаяИнформацияКлассификаторСвойстваСвойство[][] свойстваField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Наименование {
        get {
            return this.наименованиеField;
        }
        set {
            this.наименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Владелец")]
    public Владелец[] Владелец {
        get {
            return this.владелецField;
        }
        set {
            this.владелецField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Группы")]
    public Группы[] Группы {
        get {
            return this.группыField;
        }
        set {
            this.группыField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Свойство", typeof(КоммерческаяИнформацияКлассификаторСвойстваСвойство), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public КоммерческаяИнформацияКлассификаторСвойстваСвойство[][] Свойства {
        get {
            return this.свойстваField;
        }
        set {
            this.свойстваField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class КоммерческаяИнформацияКлассификаторСвойстваСвойство {
    
    private string идField;
    
    private string наименованиеField;
    
    private string обязательноеField;
    
    private string множественноеField;
    
    private string типЗначенийField;
    
    private string дляТоваровField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Наименование {
        get {
            return this.наименованиеField;
        }
        set {
            this.наименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Обязательное {
        get {
            return this.обязательноеField;
        }
        set {
            this.обязательноеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Множественное {
        get {
            return this.множественноеField;
        }
        set {
            this.множественноеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ТипЗначений {
        get {
            return this.типЗначенийField;
        }
        set {
            this.типЗначенийField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ДляТоваров {
        get {
            return this.дляТоваровField;
        }
        set {
            this.дляТоваровField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class КоммерческаяИнформацияПакетПредложений {
    
    private string идField;
    
    private string идКлассификатораField;
    
    private string наименованиеField;
    
    private Владелец[] владелецField;
    
    private КоммерческаяИнформацияПакетПредложенийТипыЦенТипЦены[][] типыЦенField;
    
    private КоммерческаяИнформацияПакетПредложенийПредложенияПредложение[][] предложенияField;
    
    private КоммерческаяИнформацияПакетПредложенийТоварыТовар[][] товарыField;
    
    private string содержитТолькоИзмененияField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ИдКлассификатора {
        get {
            return this.идКлассификатораField;
        }
        set {
            this.идКлассификатораField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Наименование {
        get {
            return this.наименованиеField;
        }
        set {
            this.наименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Владелец")]
    public Владелец[] Владелец {
        get {
            return this.владелецField;
        }
        set {
            this.владелецField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ТипЦены", typeof(КоммерческаяИнформацияПакетПредложенийТипыЦенТипЦены), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public КоммерческаяИнформацияПакетПредложенийТипыЦенТипЦены[][] ТипыЦен {
        get {
            return this.типыЦенField;
        }
        set {
            this.типыЦенField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Предложение", typeof(КоммерческаяИнформацияПакетПредложенийПредложенияПредложение), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public КоммерческаяИнформацияПакетПредложенийПредложенияПредложение[][] Предложения {
        get {
            return this.предложенияField;
        }
        set {
            this.предложенияField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Товар", typeof(КоммерческаяИнформацияПакетПредложенийТоварыТовар), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public КоммерческаяИнформацияПакетПредложенийТоварыТовар[][] Товары {
        get {
            return this.товарыField;
        }
        set {
            this.товарыField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string СодержитТолькоИзменения {
        get {
            return this.содержитТолькоИзмененияField;
        }
        set {
            this.содержитТолькоИзмененияField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class КоммерческаяИнформацияПакетПредложенийТипыЦенТипЦены {
    
    private string идField;
    
    private string наименованиеField;
    
    private string иДЦенаСайтField;
    
    private string валютаField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Наименование {
        get {
            return this.наименованиеField;
        }
        set {
            this.наименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ИДЦенаСайт {
        get {
            return this.иДЦенаСайтField;
        }
        set {
            this.иДЦенаСайтField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Валюта {
        get {
            return this.валютаField;
        }
        set {
            this.валютаField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class КоммерческаяИнформацияПакетПредложенийПредложенияПредложение {
    
    private string идField;
    
    private КоммерческаяИнформацияПакетПредложенийПредложенияПредложениеЦеныЦена[][] ценыField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Цена", typeof(КоммерческаяИнформацияПакетПредложенийПредложенияПредложениеЦеныЦена), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public КоммерческаяИнформацияПакетПредложенийПредложенияПредложениеЦеныЦена[][] Цены {
        get {
            return this.ценыField;
        }
        set {
            this.ценыField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class КоммерческаяИнформацияПакетПредложенийПредложенияПредложениеЦеныЦена {
    
    private string представлениеField;
    
    private string идТипаЦеныField;
    
    private string иДЦенаСайтField;
    
    private string ценаЗаЕдиницуField;
    
    private string валютаField;
    
    private string единицаField;
    
    private string коэффициентField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Представление {
        get {
            return this.представлениеField;
        }
        set {
            this.представлениеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ИдТипаЦены {
        get {
            return this.идТипаЦеныField;
        }
        set {
            this.идТипаЦеныField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ИДЦенаСайт {
        get {
            return this.иДЦенаСайтField;
        }
        set {
            this.иДЦенаСайтField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ЦенаЗаЕдиницу {
        get {
            return this.ценаЗаЕдиницуField;
        }
        set {
            this.ценаЗаЕдиницуField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Валюта {
        get {
            return this.валютаField;
        }
        set {
            this.валютаField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Единица {
        get {
            return this.единицаField;
        }
        set {
            this.единицаField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Коэффициент {
        get {
            return this.коэффициентField;
        }
        set {
            this.коэффициентField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class КоммерческаяИнформацияПакетПредложенийТоварыТовар {
    
    private string идField;
    
    private string артикулField;
    
    private string кодТовараField;
    
    private string наименованиеField;
    
    private string полноеНаименованиеField;
    
    private string базоваяЕдиницаField;
    
    private string описаниеField;
    
    private Группы[] группыField;
    
    private КоммерческаяИнформацияПакетПредложенийТоварыТоварЗначенияСвойствЗначенияСвойства[][] значенияСвойствField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Артикул {
        get {
            return this.артикулField;
        }
        set {
            this.артикулField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string КодТовара {
        get {
            return this.кодТовараField;
        }
        set {
            this.кодТовараField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Наименование {
        get {
            return this.наименованиеField;
        }
        set {
            this.наименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ПолноеНаименование {
        get {
            return this.полноеНаименованиеField;
        }
        set {
            this.полноеНаименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string БазоваяЕдиница {
        get {
            return this.базоваяЕдиницаField;
        }
        set {
            this.базоваяЕдиницаField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Описание {
        get {
            return this.описаниеField;
        }
        set {
            this.описаниеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Группы")]
    public Группы[] Группы {
        get {
            return this.группыField;
        }
        set {
            this.группыField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ЗначенияСвойства", typeof(КоммерческаяИнформацияПакетПредложенийТоварыТоварЗначенияСвойствЗначенияСвойства), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public КоммерческаяИнформацияПакетПредложенийТоварыТоварЗначенияСвойствЗначенияСвойства[][] ЗначенияСвойств {
        get {
            return this.значенияСвойствField;
        }
        set {
            this.значенияСвойствField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class КоммерческаяИнформацияПакетПредложенийТоварыТоварЗначенияСвойствЗначенияСвойства {
    
    private string идField;
    
    private string наименованиеField;
    
    private string значениеField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ид {
        get {
            return this.идField;
        }
        set {
            this.идField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Наименование {
        get {
            return this.наименованиеField;
        }
        set {
            this.наименованиеField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Значение {
        get {
            return this.значениеField;
        }
        set {
            this.значениеField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Владелец", typeof(Владелец))]
    [System.Xml.Serialization.XmlElementAttribute("Группы", typeof(Группы))]
    [System.Xml.Serialization.XmlElementAttribute("КоммерческаяИнформация", typeof(КоммерческаяИнформация))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
